name: coverage
on: push

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install
        run: yarn install
      - name: test+coverage
        run: yarn hardhat coverage
      - name: upload artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: coverage
          path: coverage
